### ISSUE TITLE
AttributeError: 'SACTrainingParameters' object has no attribute 'thrift_spec'

### ISSUE THREAD

**Issue by jxstanford** [facebookresearch/Horizon#67]
Hi,

I successfully installed via the docker instructions, but when trying to install locally I get the error below when running the test step.  I've got a custom tensorflow build that works with Cuda 10.0/CudaNN 7.4 running on the host, so that may be a factor, but seems unlikely.  The installation instructions say to set `JAVA_HOME` to the parent of the python dir. I don't have Java installed there, so that might also be a factor. In my case this is `/home/jxstanford/.pyenv`

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): source
TensorFlow version: r1.12 and master (7561099fb65c18bd091751b60fc45550fc5d4805)
Python version: Python 3.6.3 :: Anaconda, Inc.
Installed using virtualenv? pip? conda?: pyenv
CUDA/cuDNN version: 10.0 / 7.4
GPU model and memory: GTX 1080ti

`
jxstanford@ryzen-1080:~/devel/conda-projects/Horizon$ python setup.py test
running test
running egg_info
writing horizon.egg-info/PKG-INFO
writing dependency_links to horizon.egg-info/dependency_links.txt
writing top-level names to horizon.egg-info/top_level.txt
reading manifest file 'horizon.egg-info/SOURCES.txt'
writing manifest file 'horizon.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    dependency_links=[],
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 215, in run
    self.run_tests()
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 238, in run_tests
    **exit_kwarg
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/main.py", line 124, in parseArgs
    self._do_discovery([])
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/home/jxstanford/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/test/gym/open_ai_gym_environment.py", line 8, in <module>
    from ml.rl.test.gym.gym_predictor import (
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/test/gym/gym_predictor.py", line 8, in <module>
    from ml.rl.training.dqn_trainer import DQNTrainer
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/training/dqn_trainer.py", line 13, in <module>
    from ml.rl.preprocessing.normalization import (
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/preprocessing/normalization.py", line 12, in <module>
    from ml.rl.thrift.core.ttypes import NormalizationParameters
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/thrift/core/ttypes.py", line 2070, in <module>
    class SACModelParameters(object):
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/thrift/core/ttypes.py", line 2087, in SACModelParameters
    }), training=SACTrainingParameters(**{
  File "/home/jxstanford/devel/conda-projects/Horizon/ml/rl/thrift/core/ttypes.py", line 1941, in __init__
    if q_network_optimizer is self.thrift_spec[2][4]:
AttributeError: 'SACTrainingParameters' object has no attribute 'thrift_spec'
`

**Comment by kittipatv** [comment]
Hi @jxstanford,
We are pushing the fix. See #66 for details.

**Comment by jxstanford** [comment]
cool. I'll verify after fix is merged.

**Comment by gterziysky** [comment]
Hi all,

I installed Horizon locally.

At first, I used the docker/requirements.txt file from branch master to set up the environment, but I got the error described in @jxstanford 's comment above. After having seen the fixes suggested in #66, I downgraded thrift & thrift-cpp to v0.10.0. This did make the tests run, but I still get a couple of failures (see below).

System setup:

`JAVA_HOME` is set to the path of the bin folder of the conda virtual environment.
I also tried to replace apache thrift by [fbthrift](https://github.com/facebook/fbthrift/blob/master/thrift/compiler/README.md) globally on the machine before seeing #66 which I haven't yet removed although I am not sure this is the cause of the problem.

System information

OS Platform and Distribution: Ubuntu 18.04
Python version: Python 3.6.6 :: Anaconda, Inc.
Installed using virtualenv? pip? conda?: conda
manually installed CUDA/cuDNN version: 10.0 / 7.4 (although conda-installed pytorch may be overshadowing this with CUDA 9.0/cuDNN 7.1)
GPU model: GTX 1070

The output of the test is the following:
`...
INFO:ml.rl.test.constant_reward.test_constant_reward:Training.. 47
INFO:ml.rl.test.constant_reward.test_constant_reward:Training epoch 47 average q values tensor(99.9338)
INFO:ml.rl.test.constant_reward.test_constant_reward:Training.. 48
INFO:ml.rl.test.constant_reward.test_constant_reward:Training epoch 48 average q values tensor(99.9236)
INFO:ml.rl.test.constant_reward.test_constant_reward:Training.. 49
INFO:ml.rl.test.constant_reward.test_constant_reward:Training epoch 49 average q values tensor(99.9184)
ok
test_add_custom_scalars (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... /path/to/Horizon/ml/rl/test/test_tensorboardX.py:73: DeprecationWarning: Please use assertRaisesRegex instead.
  AssertionError, "Title \(title\) is already in category \(cat\)"
ok
test_global_step (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... ok
test_noop (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... ok
test_with_none (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... ok
test_writing (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... FAIL
test_writing_stack (ml.rl.test.test_tensorboardX.TestSummaryWriterContext) ... FAIL

======================================================================
FAIL: test_writing (ml.rl.test.test_tensorboardX.TestSummaryWriterContext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/Horizon/ml/rl/test/test_tensorboardX.py", line 28, in test_writing
    "test", torch.ones(1), global_step=0
  File "/home/galen/anaconda3/envs/testenv/lib/python3.6/unittest/mock.py", line 825, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/home/galen/anaconda3/envs/testenv/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: mock('test', tensor([1.]), global_step=0)
Actual call: mock('test', tensor([1.]), global_step=1)

======================================================================
FAIL: test_writing_stack (ml.rl.test.test_tensorboardX.TestSummaryWriterContext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/Horizon/ml/rl/test/test_tensorboardX.py", line 42, in test_writing_stack
    "test1", torch.zeros(1), global_step=0
  File "/home/galen/anaconda3/envs/testenv/lib/python3.6/unittest/mock.py", line 825, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/home/galen/anaconda3/envs/testenv/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: mock('test1', tensor([0.]), global_step=0)
Actual call: mock('test1', tensor([0.]), global_step=1)

----------------------------------------------------------------------
Ran 103 tests in 190.402s

FAILED (failures=2, skipped=1)
Test failed: <unittest.runner.TextTestResult run=103 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=103 errors=0 failures=2>`

Your help would be much appreciated.

**Comment by MisterTea** [comment]
I've seen that fail before.  What OS are you running?

**Comment by MisterTea** [comment]
Nevermind, I saw you posted your OS :-P
